# Generated by Django 4.1.2 on 2022-10-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='language',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='send_email',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
