version: '3.8'

services:
  web:
    image: my-django-app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - django_net
    env_file:
      - ./.env

  db:
    image: postgres:latest
    networks:
      - django_net
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  django_net:
    driver: bridge
