version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    networks:
      - django_net
    env_file:
      - ./.env

  db:
    image: postgres
    ports:
      - 5422:5422
    networks:
      - django_net
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  django_net:
    driver: bridge